# This file is part of Flask-AppExts
# Copyright (C) 2015 CERN.
#
# Flask-AppExts is free software; you can redistribute it and/or
# modify it under the terms of the Revised BSD License; see LICENSE
# file for more details.

[pytest]
addopts = --clearcache --pep8 --ignore=docs --cov=flask_appexts --cov-report=term-missing tests flask_appexts
